// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdlarflcrbdhrqkjsnfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbGFyZmxjcmJkaHJxa2pzbmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTY4MzYsImV4cCI6MjA3MzM3MjgzNn0.v-h3B0fZq8b2wLNgK4nvXPoH5MDjyBhMR3FYvriUrWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});